version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.9
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
